const {chromium,expect}=require('@playwright/test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try {
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 await page.goto(process.env.SITE_URL||'http://127.0.0.1:4173/');
 await page.locator('.contact-intent').waitFor();
 const heroVideo=page.locator('.hero-motion-video');
 await expect(heroVideo).toHaveCount(1);
 await page.waitForTimeout(600);
 const heroVideoState=await heroVideo.evaluate(video=>({autoplay:video.autoplay,muted:video.muted,loop:video.loop,playsInline:video.playsInline,paused:video.paused,currentSrc:video.currentSrc}));
 assert.deepEqual({autoplay:heroVideoState.autoplay,muted:heroVideoState.muted,loop:heroVideoState.loop,playsInline:heroVideoState.playsInline,paused:heroVideoState.paused},{autoplay:true,muted:true,loop:true,playsInline:true,paused:false});
 assert.match(heroVideoState.currentSrc,/agencia-mello-hero-motion\.(webm|mp4)$/);
 assert.equal(await page.locator('.hero-project').count(),0);
 assert.equal(await page.locator('.contact-line').count(),3);
 assert.equal(await page.locator('.contact-composition a').count(),0,'O título editorial não deve ignorar a intenção de contato.');
 assert.ok(new URL(await page.locator('.intent-send').getAttribute('href')).searchParams.get('text').includes('Meu negócio'),'Contato disponível sem escolher um serviço.');
  const primary=page.locator('.primary-cta');
  await primary.scrollIntoViewIfNeeded();
  await page.mouse.move(0,0);
  const primaryBox=await primary.boundingBox();
  const primaryColor=await primary.evaluate(element=>getComputedStyle(element).backgroundColor);
  const primaryHref=await primary.getAttribute('href');
  const primaryUrl=new URL(primaryHref);
  assert.equal(primaryUrl.pathname,'/5521971859948');
  assert.ok(primaryUrl.searchParams.get('text'));
  await primary.hover({position:{x:20,y:15}});
  await expect.poll(()=>primary.evaluate(element=>getComputedStyle(element).backgroundColor)).not.toBe(primaryColor);
  const hoverBox=await primary.boundingBox();
  assert.ok(Math.abs(hoverBox.width-primaryBox.width)<.1 && Math.abs(hoverBox.height-primaryBox.height)<.1,'Hover não pode redimensionar o CTA.');
  assert.ok(Math.abs(hoverBox.x-primaryBox.x)<=3 && Math.abs(hoverBox.y-primaryBox.y)<=3,'O magnetismo do CTA deve ser sutil.');
  await page.setViewportSize({width:390,height:844});
  await expect(primary).toBeVisible();
  await expect(primary).toHaveAttribute('href',primaryHref);
 await page.setViewportSize({width:1440,height:900});
 for(const [key,word] of [['sites','um site pro meu negócio'],['identidade','identidade visual'],['conteudo','peças pras redes sociais']]){
  await page.locator('.intent-options label').filter({has:page.locator(`input[value="${key}"]`)}).click();
  await expect(page.locator(`input[value="${key}"]`)).toBeChecked();
  const href=await page.locator('.intent-send').getAttribute('href');
  const url=new URL(href);
  assert.equal(url.pathname,'/5521971859948');
  assert.ok(url.searchParams.get('text').includes(word));
 }
 await page.locator('input[value="sites"]').focus();
 await page.keyboard.press('ArrowRight');
 await expect(page.locator('input[value="identidade"]')).toBeChecked();
 await page.emulateMedia({reducedMotion:'reduce'});
 await expect(page.locator('.hero-motion-video')).toHaveCount(0);
 await expect(page.locator('.brand-sculpture-static img')).toHaveCount(1);
 await expect.poll(()=>page.locator('.contact-line>b').first().evaluate(e=>e.style.transform)).toBe('');
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
 fs.mkdirSync('artifacts',{recursive:true});
 await page.screenshot({path:'artifacts/sprint-confirm-hero.png'});
 await page.setViewportSize({width:390,height:844});
 await page.locator('.contact-intent').scrollIntoViewIfNeeded();
 await page.screenshot({path:'artifacts/sprint-confirm-contact.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  console.log('Sprint: CTA estável, feedback de hover, destino, três mensagens, teclado e reduced motion verificados.');
 } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exit(1)});
