import React from 'react';
import { StudioShell, SectionLabel, usePageTitle } from '../components/studio/Studio';
import { SITE_ESSENCIAL_CONDITIONS, SITE_ESSENCIAL_FAQS, SITE_ESSENCIAL_MESSAGES, SITE_ESSENCIAL_INCLUDED_LIST, SITE_ESSENCIAL_PROCESS_STEPS, getWhatsAppUrl } from '../data/siteData';
export function SiteEssencialPage(){
  usePageTitle('Site Essencial R$ 500 | Prévia grátis, pague só se aprovar | Mello');
  return <StudioShell contact={false}>
    <section className="essential-hero wrap"><SectionLabel number="Mello / Essencial">Para negócios locais</SectionLabel><h1>Seu negócio no ar.<br/>Você vê pronto<br/><span>antes de pagar.</span></h1><div className="essential-layout"><div><p>Um site de uma página que mostra seus serviços, organiza as informações do negócio e leva o cliente direto pro seu WhatsApp.</p><p style={{marginTop:20}}>A gente manda uma prévia privada e gratuita. Você só paga se gostar.</p></div><div className="essential-buy"><strong>R$ 500</strong><small>em até 3x, só depois de aprovar</small><br/><a className="solid-link" href={getWhatsAppUrl(SITE_ESSENCIAL_MESSAGES.hero)} target="_blank" rel="noreferrer">Quero ver minha prévia <span aria-hidden="true">↗</span></a><p>O que está incluso é definido antes. Publicação só depois da sua aprovação.<br/>{SITE_ESSENCIAL_CONDITIONS.domain}<br/>Hospedagem sem mensalidade na Netlify, dentro dos limites do plano gratuito.</p></div></div></section>
    <section id="incluso" className="essential-scope"><div className="wrap"><SectionLabel number="01">O que você está contratando</SectionLabel><div className="scope-grid"><div><h3>O essencial, bem resolvido.</h3><ul>{SITE_ESSENCIAL_INCLUDED_LIST.map(item=><li key={item}>{item}</li>)}</ul></div><div><h3>Precisa de algo além?</h3><p>Loja virtual, pagamento online, área de login, cadastro de usuários, painel administrativo e várias páginas: orçamento à parte.</p></div></div><p className="scope-note">Os R$ 500 valem pra este formato. {SITE_ESSENCIAL_CONDITIONS.domain} {SITE_ESSENCIAL_CONDITIONS.hosting} Alterações e suporte após a entrega são combinados à parte.</p><p className="scope-note">{SITE_ESSENCIAL_CONDITIONS.timing}</p></div></section>
    <section id="como-funciona" className="essential-process wrap"><SectionLabel number="02">Da conversa à publicação</SectionLabel><h2>Você vê.<br/>Você aprova.</h2><div className="process-grid">{SITE_ESSENCIAL_PROCESS_STEPS.map(step=><div key={step.n}><span className="micro">{step.n}</span><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></section>
    <section id="duvidas" className="essential-faq wrap"><h2>Antes de começar.</h2>{SITE_ESSENCIAL_FAQS.map(faq=><details key={faq.q}><summary>{faq.q}</summary><p>{faq.a}</p></details>)}</section>
    <section className="studio-contact"><div className="wrap"><SectionLabel number="03">Bora?</SectionLabel><a className="contact-title" href={getWhatsAppUrl(SITE_ESSENCIAL_MESSAGES.ctaFinal)} target="_blank" rel="noreferrer">Peça sua<br/>prévia.<span aria-hidden="true">↗</span></a><p>Chama no WhatsApp e peça sua prévia. Sem pagamento antecipado.</p></div></section>
  </StudioShell>;
}
