import { ContactLink, SectionLabel } from './Studio';

const services = [
  { id:'web', name:'Sites e landing pages', line:'Apresente seu negócio.\nFacilite o contato.', text:'Sites institucionais e landing pages que organizam seus serviços, apresentam sua marca e facilitam o contato pelo WhatsApp.', tags:['Sites institucionais','Landing pages','WhatsApp integrado'], key:'sites' },
  { id:'marca', name:'Identidade visual', line:'Uma marca fácil\nde reconhecer.', text:'Logo, cores, tipografia e direção visual para dar consistência à apresentação da sua marca, do site aos materiais de divulgação.', tags:['Logo','Cores e tipografia','Direção visual'], key:'identidade' },
  { id:'conteudo', name:'Design para redes sociais', line:'Sua identidade.\nEm cada publicação.', text:'Posts, carrosséis e peças de campanha com a linguagem da sua marca. Formatos e quantidade são definidos conforme a necessidade do projeto.', tags:['Posts e carrosséis','Peças de campanha','Materiais promocionais'], key:'conteudo' },
];

function ServiceVisual({ index }: {index: number}) {
  if (index === 0) return <div className="service-visual visual-web" aria-hidden="true"><div className="mini-browser"><div className="browser-chrome"><i/><i/><i/><span>Uma experiência em cada detalhe</span></div><img src="/assets/portfolio-restaurant.webp" alt="" loading="lazy" width="1024" height="768"/></div><span className="visual-footnote">Estudo Bellavista / Direção digital</span></div>;
  if (index === 1) return <div className="service-visual visual-brand" aria-hidden="true"><span className="brand-specimen">Aa<span>→</span></span><div className="brand-swatches"><i/><i/><i/></div><span className="brand-specimen-label">Forma. Cor. Personalidade.</span><img src="/assets/agencia-mello-icone.png" alt="" width="292" height="289" loading="lazy"/></div>;
  return <div className="service-visual visual-content" aria-hidden="true"><div className="social-sheet sheet-one"><small>MELLO / IDEIAS EM CIRCULAÇÃO</small><strong>Quem é<br/>visto.<br/><em>É lembrado.</em></strong><span>Design + conteúdo ↗</span></div><div className="social-sheet sheet-two"><span>Presença<br/>se constrói.</span><img src="/assets/agencia-mello-icone.png" alt="" width="292" height="289" loading="lazy"/><small>UM PONTO DE CONTATO POR VEZ.</small></div></div>;
}

export function ExperienceServices() {
  return <section className="experience-services" id="servicos" data-chapter="Serviços"><div className="wrap service-narrative"><aside className="service-directory"><SectionLabel number="02">O que fazemos</SectionLabel><h2>Sua marca.<br/>Bem<br/>{' '}<span>apresentada.</span></h2><p>Sites, identidade visual e peças de conteúdo, com escopo definido para cada projeto.</p><nav aria-label="Índice de serviços">{services.map((service,index)=><a key={service.id} href={`#servico-${service.id}`} data-service-nav={index}><span>0{index+1}</span>{service.name}<i aria-hidden="true">↗</i></a>)}</nav></aside><div className="service-chapters">{services.map((service,index)=><article key={service.id} id={`servico-${service.id}`} className="service-chapter" data-service-index={index}><div className="service-chapter-top"><span className="micro">0{index+1} / {service.name}</span><span aria-hidden="true">↗</span></div><ServiceVisual index={index}/><h3>{service.line.split('\n').map((line,i)=><span key={line}>{i>0&&<br/>}{line}</span>)}</h3><p>{service.text}</p><ul className="service-tags" data-reveal="stagger">{service.tags.map(tag=><li key={tag}>{tag}</li>)}</ul><ContactLink messageKey={service.key} className="text-link">Converse sobre {index===0?'seu site':index===1?'sua identidade':'suas peças'} <span aria-hidden="true">↗</span></ContactLink></article>)}</div></div></section>;
}
