import { ContactLink, SectionLabel } from './Studio';

const services = [
  { id:'web', name:'Sites e landing pages', line:'Seu cliente entende o que você faz.\nE chama no WhatsApp.', text:'Sites institucionais e landing pages que mostram seus serviços, passam confiança e levam direto pro seu WhatsApp.', tags:['Sites institucionais','Landing pages','WhatsApp integrado'], key:'sites' },
  { id:'marca', name:'Identidade visual', line:'Sua marca para de\nparecer improvisada.', text:'Criamos o sistema visual que faz tudo parecer parte da mesma marca.', tags:['Logo','Cores e tipografia','Direção visual'], key:'identidade' },
  { id:'conteudo', name:'Design para redes sociais', line:'Chega de cada post\nnum estilo.', text:'Posts, carrosséis e peças de campanha no mesmo padrão da sua marca. Formatos e quantidade são definidos conforme a necessidade do projeto.', tags:['Posts e carrosséis','Peças de campanha','Materiais promocionais'], key:'conteudo' },
];

function ServiceVisual({ index }: {index: number}) {
  if (index === 0) return <div className="service-visual visual-web" aria-hidden="true"><div className="mini-browser"><div className="browser-chrome"><i/><i/><i/><span>Do primeiro olhar ao primeiro contato</span></div><img src="/assets/portfolio-restaurant.webp" alt="" loading="lazy" width="1024" height="768"/></div><span className="visual-footnote">Estudo Bellavista / Site</span></div>;
  if (index === 1) return <div className="service-visual visual-brand" aria-hidden="true"><span className="brand-specimen">Aa<span>→</span></span><div className="brand-swatches"><i/><i/><i/></div><span className="brand-specimen-label">Forma. Cor. Personalidade.</span><img src="/assets/agencia-mello-icone.png" alt="" width="292" height="289" loading="lazy"/></div>;
  return <div className="service-visual visual-content" aria-hidden="true"><div className="social-sheet sheet-one"><small>MELLO / IDEIAS EM CIRCULAÇÃO</small><strong>CONSISTÊNCIA<br/>GERA<br/><em>CONFIANÇA.</em></strong><span>Design + conteúdo ↗</span></div><div className="social-sheet sheet-two"><span>Marca forte<br/>se constrói<br/>post a post.</span><img src="/assets/agencia-mello-icone.png" alt="" width="292" height="289" loading="lazy"/><small>UM PONTO DE CONTATO POR VEZ.</small></div></div>;
}

export function ExperienceServices() {
  return <section className="experience-services" id="servicos" data-chapter="Serviços"><div className="wrap service-narrative"><aside className="service-directory"><SectionLabel number="02">O que fazemos</SectionLabel><h2>Do site ao post,<br/>tudo com a<br/><span>mesma cara.</span></h2><p>Sites, identidade visual e conteúdo. Você sabe o que vai receber antes de fechar.</p><nav aria-label="Índice de serviços">{services.map((service,index)=><a key={service.id} href={`#servico-${service.id}`} data-service-nav={index}><span>0{index+1}</span>{service.name}<i aria-hidden="true">↗</i></a>)}</nav></aside><div className="service-chapters">{services.map((service,index)=><article key={service.id} id={`servico-${service.id}`} className="service-chapter" data-service-index={index}><div className="service-chapter-top"><span className="micro">0{index+1} / {service.name}</span><span aria-hidden="true">↗</span></div><ServiceVisual index={index}/><h3>{service.line.split('\n').map((line,i)=><span key={line}>{i>0&&<br/>}{line}</span>)}</h3><p>{service.text}</p><ul className="service-tags" data-reveal="stagger">{service.tags.map(tag=><li key={tag}>{tag}</li>)}</ul><ContactLink messageKey={service.key} className="text-link">{index===0?'Quero ver meu site pronto':index===1?'Quero minha identidade visual':'Quero peças com a minha cara'} <span aria-hidden="true">↗</span></ContactLink></article>)}</div></div></section>;
}
